import type { Metadata } from 'next'

import { Footer } from '@/components/Footer'
import { Header } from '@/components/Header'
import { Providers } from '@/providers'

import './globals.css'

export const metadata: Metadata = {
	title: 'Next blog',
	description: 'Generated by create next app',
}

interface Props {
	children: React.ReactNode
}

export default function RootLayout({ children }: Props) {
	return (
		<html lang='en'>
			<body>
				<Providers>
					<Header />
					<main className='main'>{children}</main>
					<Footer />
				</Providers>
			</body>
		</html>
	)
}
