import type { Metadata } from 'next'

import { Footer } from '@/components/Footer'
import { Header } from '@/components/Header'

import './globals.css'

export const metadata: Metadata = {
	title: 'Next blog',
	description: 'Generated by create next app',
}

interface RootLayoutProps {
	children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
	return (
		<html lang='en'>
			<body>
				<Header />
				<main className='main'>{children}</main>
				<Footer />
			</body>
		</html>
	)
}
